# Generated by Django 5.1.15 on 2026-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='proof_photo',
            field=models.TextField(blank=True, default='', help_text='Proof photo URL or an uploaded data: URL'),
        ),
    ]
