# Generated by Django 5.1.15 on 2026-06-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_deliveryassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='cod_paid_via_upi',
            field=models.BooleanField(default=False),
        ),
    ]
