# Generated by Django 5.1.15 on 2026-06-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_is_returned_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Target delivery date. Set to the next day for next-day pre-orders.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('instant', 'Instant'), ('next_day', 'Next day')], default='instant', help_text='Instant (same-day) or a next-day pre-order placed during the ordering window.', max_length=10),
        ),
    ]
