# Generated by Django 5.1.15 on 2026-06-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('support', 'Support agent'), ('ops', 'Operations'), ('warehouse', 'Warehouse'), ('admin', 'Administrator')], default='customer', max_length=12),
        ),
    ]
