# Generated by Django 5.1.15 on 2026-06-27 07:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('199'), help_text='Order subtotal at/above which delivery is free.', max_digits=8)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('25'), help_text='Delivery charge below the free-delivery threshold. 0 = always free.', max_digits=8)),
                ('small_cart_threshold', models.DecimalField(decimal_places=2, default=Decimal('99'), help_text='Subtotal below which a small-cart fee applies. 0 = never.', max_digits=8)),
                ('small_cart_fee', models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='Small-cart fee amount. 0 = no small-cart fee.', max_digits=8)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Tax percentage applied to the taxable amount. 0 = no tax.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store configuration',
                'verbose_name_plural': 'Store configuration',
                'db_table': 'store_config',
            },
        ),
    ]
