# Generated by Django 5.1.15 on 2026-06-29 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='next_day_enabled',
            field=models.BooleanField(default=False, help_text='Allow customers to pre-order for next-day delivery during the daily window.'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='next_day_window_end',
            field=models.TimeField(default=datetime.time(10, 0), help_text='Time of day the next-day ordering window closes (store local time).'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='next_day_window_start',
            field=models.TimeField(default=datetime.time(6, 0), help_text='Time of day the next-day ordering window opens (store local time).'),
        ),
    ]
