# Generated by Django 5.1.15 on 2026-06-14 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('catalog', '0002_remove_product_mrp_remove_product_price_and_more'),
        ('orders', '0005_order_coupon_order_delivery_fee_order_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Default units delivered per day')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('alternate', 'Alternate days'), ('weekdays', 'Weekdays (Mon–Fri)'), ('custom', 'Custom calendar')], max_length=10)),
                ('custom_days', models.JSONField(blank=True, default=list, help_text="For CUSTOM frequency: list of ISO dates, e.g. ['2026-06-20', '2026-06-22']")),
                ('preferred_time', models.TimeField(blank=True, help_text='Preferred morning delivery time', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='addresses.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'subscription_vacations',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('skipped', 'Skipped'), ('delivered', 'Delivered'), ('failed_balance', 'Failed — insufficient balance')], default='scheduled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_deliveries', to='orders.order')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'subscription_deliveries',
                'ordering': ['-date'],
                'unique_together': {('subscription', 'date')},
            },
        ),
    ]
