# Generated by Django 5.1.15 on 2026-06-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'MilkKart Wallet'), ('cod', 'Cash on Delivery')], default='wallet', help_text='How each delivery is paid: wallet auto-debit or cash on delivery', max_length=10),
        ),
    ]
