# Generated by Django 5.1.15 on 2026-06-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.CharField(blank=True, default='', help_text='Background image URL/path', max_length=500)),
                ('link_url', models.CharField(blank=True, default='', help_text='Where the banner links to', max_length=500)),
                ('bg_color', models.CharField(blank=True, default='', help_text='CSS background when no image, e.g. #def9ec', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
