# Generated by Django 5.1.15 on 2026-06-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bg_color',
            field=models.CharField(blank=True, default='', help_text='CSS background when no image', max_length=40),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.TextField(blank=True, default='', help_text='Background image URL/path, or an uploaded data: URL'),
        ),
    ]
