# Generated by Django 5.1.15 on 2026-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online'), ('wallet', 'MilkKart Wallet')], max_length=10),
        ),
    ]
