# Generated by Django 5.1.15 on 2026-06-14 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_rating_count_product_rating_sum'),
        ('orders', '0005_order_coupon_order_delivery_fee_order_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Signed change in stock (+restock, -sale)')),
                ('reason', models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale'), ('cancellation', 'Cancellation'), ('subscription', 'Subscription'), ('adjustment', 'Manual adjustment'), ('damage', 'Damage / wastage')], max_length=15)),
                ('balance_after', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', '-created_at'], name='stock_movem_variant_5b86c0_idx')],
            },
        ),
    ]
