# Generated by Django 5.1.15 on 2026-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon_order_delivery_fee_order_discount_and_more'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettopup',
            name='gateway_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_txn_recent_idx'),
        ),
    ]
