# Generated by Django 5.1.15 on 2026-06-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('polygon', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher wins when zones overlap (e.g. a small zone over a big one)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_zones',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
