# Generated by Django 5.1.15 on 2026-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceability', '0002_deliveryzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('notified', models.BooleanField(default=False, help_text="Set once we've told them their area went live")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Waitlist entries',
                'db_table': 'serviceability_waitlist',
                'ordering': ['-created_at'],
                'unique_together': {('phone', 'pincode')},
            },
        ),
    ]
