# Generated by Django 5.1.15 on 2026-06-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_rating_count_product_rating_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Product image URL or path', max_length=500),
        ),
    ]
